landuses = {
    "drinking": {"amenity": ["bar", "biergarten", "pub"]},
    "beverage": {"amenity": ["cafe"]},
    "eating": {"amenity": ["fast_food", "food_court", "ice_cream", "restaurant"]},
    "children": {"amenity": ["kindergarten", "school", "childcare"], "leisure": ["playground"]},
    "education": {
        "amenity": ["college", "language_school", "research_institute", "training", "university", "music_school"]
    },
    "transport": {
        "amenity": ["bicycle_parking", "bicycle_rental", "bus_station", "car_sharing", "ferry_terminal", "taxi"],
        "highway": ["bus_stop"],
        "public_transport": ["station"],
    },
    "healthcare": {
        "amenity": [
            "clinic",
            "dentist",
            "doctors",
            "hospital",
            "nursing_home",
            "pharmacy",
            "social_facility",
            "veterinary",
        ],
        "healthcare": ["*"],
    },
    "office": {"office": ["*"]},
    "grocery": {
        "shop": [
            "alcohol",
            "bakery",
            "beverages",
            "brewing_supplies",
            "butcher",
            "cheese",
            "chocolate",
            "coffee",
            "confectionery",
            "convenience",
            "deli",
            "dairy",
            "farm",
            "frozen_food",
            "greengrocer",
            "health_food",
            "ice_cream",
            "pasta",
            "pastry",
            "seafood",
            "spices",
            "tea",
            "wine",
        ]
    },
    "retail_store": {"shop": ["department_store", "general", "kiosk", "mall", "supermarket", "wholesale"]},
    "clothing_store": {
        "shop": [
            "baby_goods",
            "bag",
            "boutique",
            "clothes",
            "fabric",
            "fashion_accessories",
            "jewelry",
            "leather",
            "sewing",
            "shoes",
            "tailor",
            "watches",
            "wool",
        ],
    },
    "health_beauty": {
        "shop": [
            "beauty",
            "chemist",
            "cosmetics",
            "hairdresser",
            "hairdresser_supply",
            "hearing_aids",
            "herbalist",
            "massage",
            "medical_supply",
            "nutrition_supplements",
            "optician",
            "perfumery",
            "tattoo",
        ]
    },
    "diy": {
        "shop": [
            "agrarian",
            "appliance",
            "bathroom_furnishing",
            "doityourself",
            "electrical",
            "energy",
            "fireplace",
            "florist",
            "garden_centre",
            "garden_furniture",
            "glaziery",
            "groundskeeping",
            "hardware",
            "houseware",
            "locksmith",
            "paint",
            "pottery",
            "security",
            "trade",
        ]
    },
    "furniture": {
        "shop": [
            "antiques",
            "bed",
            "candles",
            "carpet",
            "curtain",
            "doors",
            "flooring",
            "furniture",
            "household_linen",
            "interior_decoration",
            "kitchen",
            "lighting",
            "tiles",
            "window_blind",
        ]
    },
    "electronics": {
        "shop": [
            "computer",
            "electronics",
            "hifi",
            "mobile_phone",
            "radiotechnics",
            "telecommunication",
            "vacuum_cleaner",
        ]
    },
    "hobby": {
        "shop": [
            "art",
            "camera",
            "collector",
            "craft",
            "frame",
            "games",
            "model",
            "music",
            "photo",
            "trophy",
            "video",
            "video_games",
        ]
    },
    "stationery": {"shop": ["anime", "books", "gift", "lottery", "newsagent", "stationery", "ticket"]},
    "other": {
        "shop": [
            "copyshop",
            "dry_cleaning",
            "laundry",
            "pawnbroker",
            "pet",
            "toys",
            "travel_agency",
        ],
        "amenity": ["internet_cafe"],
    },
    "civic": {
        "amenity": [
            "arts_centre",
            "planetarium",
            "theatre",
            "library",
            "courthouse",
            "fire_station",
            "police",
            "post_office",
            "townhall",
            "community_centre",
            "social_centre",
            "marketplace",
        ],
    },
    "entertainment": {
        "amenity": [
            "casino",
            "cinema",
            "conference_centre",
            "events_venue",
            "exhibition_centre",
            "music_venue",
            "nightclub",
        ]
    },
    "active": {
        "leisure": [
            "fitness_centre",
            "fitness_station",
            "horse_riding",
            "ice_rink",
            "miniature_golf",
            "sports_centre",
            "swimming_area",
            "swimming_pool",
            "track",
            "water_park",
        ]
    },
    "religious": {"amenity": ["place_of_worship"]},
    "craft": {"craft": ["*"]},
    "sport": {"sport": ["*"]},
    "tourism": {"tourism": ["*"], "historic": ["*"]},
}
